### ISSUE TITLE
Highlight also directories

### ISSUE THREAD

**Issue by andreiucm** [karabaja4/vscode-explorer-git-status#1]
Atom Highlight also the directories.  Will be very useful if the hack will do this functionality too

**Comment by karabaja4** [comment]
Fixed with 9300617. Explorer behavior should be identical to Atom now.

To install, replace the function in `workbench.main.js` you added before with the new one from `dist.min.js`.

**Comment by andreiucm** [comment]
Work well. Thank you very much!
